#!groovy

// Generated by IBM TransformationAdvisor
// Fri Feb 08 14:51:33 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}